### ISSUE TITLE
Where are the videos?

### ISSUE THREAD

**Issue by BaileyJM02** [PacktPublishing/Hands-on-Microservices-with-Go#1]
Hi, sorry to have to make an issue but I’ve looked in the documentation and on the website and can’t find any links to the mentioned videos. Could someone help me please?

**Comment by ghost** [comment]
Hi @BaileyJM02, this repo is the source code for a video course that will be published by Packt Publishing. Unfortunately there have been some delays on the editing of the videos, so the course is not yet available. I will keep you updated once the course is online.

**Comment by BaileyJM02** [comment]
Is there a current ETA?

**Comment by ghost** [comment]
There have been some issues with editing that are beyond my control, but I'm thinking that it should probably be published by the beginnings of May. Best regards, and thank you for your interest.

**Comment by BaileyJM02** [comment]
https://www.packtpub.com/product/hands-on-microservices-with-go-video/9781788993999
