### ISSUE TITLE
Postman collection - S2V1.postman_collection.json does not exist

### ISSUE THREAD

**Issue by folleymcklaukyn** [PacktPublishing/Hands-on-Microservices-with-Go#8]
Hi,
The file S2V1.postman_collection.json does not exist.  Instead, in the folder github.com\PacktPublishing\Hands-on-Microservices-with-Go\section-2\video-1 is a copy of S1V6.postman_collection.json.  You can see all the json files in the repo in this image.
![screenshot](https://user-images.githubusercontent.com/11838905/104914943-a4238d00-596e-11eb-9483-291688448cc4.png)

**Comment by emluque** [comment]
Hi @folleymcklaukyn , I have just restored the file. Thank you for reporting the issue, best regards,
Emiliano
